const TestimonialApi = [
  {
    id: 1,
    image: "./img/slide1.png",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    offcer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Marcent Of Vanice and treatement. Ut tincidunt est ac dolor aliquam sodales",
  },
  {
    id: 2,
    image: "./image/slide1.png",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    offcer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Marcent Of Vanice and treatement. Ut tincidunt est ac dolor aliquam sodales",
  },
  {
    id: 3,
    image: "./image/slide1.png",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    offcer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Marcent Of Vanice and treatement. Ut tincidunt est ac dolor aliquam sodales",
  },
  {
    id: 4,
    image: "./image/slide1.png",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    offcer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Marcent Of Vanice and treatement. Ut tincidunt est ac dolor aliquam sodales",
  },
  {
    id: 5,
    image: "./image/slide1.png",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    offcer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Marcent Of Vanice and treatement. Ut tincidunt est ac dolor aliquam sodales",
  },
];

export default TestimonialApi